import Head from "next/head";
import React from "react";

export default function Post({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>EuroAsia Consulting PVT Limited | Post Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{data?.title}</h1>
        <p>{data?.body}</p>
      </div>
    </>
  );
}

export async function getStaticPaths() {
  const response = await fetch(`https://jsonplaceholder.typicode.com/posts`);

  const posts = await response.json();

  const paths = posts.map((elm) => {
    return {
      params: {
        id: elm.id.toString(),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const { params } = context;

  const response = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${params.id}`
  );

  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
