import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function about({ posts }) {
  
  return (
    <>
      <Head>
        <title>EuroAsia Consulting PVT Limited | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About Us Data Fetching Here!</h1>
      <ul>
        {posts.map((elm, index) => (
          <li key={index}>
            <Link href={`/post/${elm.id}`}>{elm?.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  let posts = await response.json();
  return {
    props: {
      posts,
    },
  };
}
